version: "3.9"

services:
  web:
    build: .
    container_name: web
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
  #   depends_on:
  #     - db

  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: ecommerce
  #     POSTGRES_USER: ecommerce_user
  #     POSTGRES_PASSWORD: ecommerce_pass
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/

# volumes:
#   postgres_data:
